### ISSUE TITLE
Ablauf des Spiels beschreiben

### ISSUE THREAD

**Issue by schiller-cc** [schiller-cc/simulate-game#2]
Beschreibe den Ablauf des Spiels.
Beginne mit dem Verhalten direkt nach den Start des Spiels.
Beschreibe dann den Verlauf einer Spielrunde.
Stelle das Ergebnis einer Spielrunde dar.
Lege fest, was am Ende des Spiels passiert.

Schön wäre dazu ein Ablaufdiagramm.

Erstelle die Datei "Ablauf.doc" und lade diese in das Git-Repository hoch.

**Comment by schiller-cc** [comment]
Hendrik macht's! :-)

**Comment by DasHendrik** [comment]
Okay :D

**Comment by schiller-cc** [comment]
Doku bitte in den Branch "Anforderungsdokumente" einfügen.
